name: 'Sec3 Pro'
description: 'This action conducts security auditing on Solana smart contracts using Sec3 Premium tool.'
inputs:
  path:
    description: "Configure the job to run tests against a specific program"
    required: false
    default: "."
  sec3-token:
    description: 'The Sec3 Secret Token that Sec3 has provided to the user'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
