name: 'Sec3 Pro'
description: 'This action conducts security auditing on Solana smart contracts using Sec3 Pro tool.'
inputs:
  path:
    description: "Configure the job to run tests against a specific program"
    required: false
    default: "."
  sec3-token:
    description: 'The token (same as the invitation code) that Sec3 has provided to the user'
    required: true
outputs:
  has-error:
    description: 'Whether Sec3 detects errors in the codebase.'
runs:
  using: 'node16'
  main: 'dist/index.js'
